channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pandas-profiling
  - ipywidgets
  - hyperopt
  - kaggle
  - plotly
  - scikit-learn
  - scipy
  - numpy
  - python
  - py-xgboost
  - jupyterlab
  - nb_conda
  - bokeh
  - pandas
  - holoviews
  - seaborn
